services:
  db:
    image: postgres:16  # Es buena práctica fijar una versión
    container_name: discord_postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cafeshop_db
    ports:
      - "5432:5432"
    volumes:
      - cafeshop_db_data:/var/lib/postgresql/data


  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ".env"
    depends_on:
          - db

volumes:
  cafeshop_db_data: